### ISSUE TITLE
Add variable for author name

### ISSUE THREAD

**Issue by rsletta** [OGKevin/obsidian-kobo-highlights-import#109]
By adding a variable for author name, it will be able to use it for linking to a author document.

**Comment by hyleore** [comment]
I came here to request this - I like to have author's names linked to their quotes and ideas in Obsidian so that would be useful, if at all possible with how Kobo readers work.

**Comment by OGKevin** [comment]
@rsletta i was under the impression that you wanted to pick this up? Is this still the case or shall I have a look?

**Comment by rsletta** [comment]
It has been my intent. See my other comment.

**Comment by OGKevin** [comment]
I had a look in the database, and it seems that it doesn't store who the author of a book is 😕
At least, in my database, the author table is empty. 

![Screenshot 2024-01-12 at 11 27 30](https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/17928966/b0530867-f60f-424a-b010-194a0f00a04a)
![Screenshot 2024-01-12 at 11 27 32](https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/17928966/676e8e8e-df2b-49da-b93f-aecbb42e600a)

So I'm a bit confused where the e-reader is pulling this information from to show in the UI 🤔

**Comment by rsletta** [comment]
The only data I found was in the content table. There is one entry where the author name is in the "attribution" column, which I assume is the ebook, based on MimeType.
<img width="1804" alt="image" src="https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/12566124/d35b8ddb-78af-4360-926e-95ac7fbaa858">
The ContentID of that row is the same as the BookID of the other rows for that book.
<img width="1824" alt="image" src="https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/12566124/696f8029-cd5f-4ed5-9ed8-a6e0a28b15ca">
<img width="1805" alt="image" src="https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/12566124/52eab532-bc4a-4946-b945-053f3a4bb2b5">

It might be that

**Comment by OGKevin** [comment]
I've managed to even include more details than just the author!
Thanks for the hint.

**Comment by OGKevin** [comment]
If anyone is available or interested to test before an official release: https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/1.6.0-beta.2
