### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Vandelante** [OGKevin/obsidian-kobo-highlights-import#143]
I'm not sure what is causing my vault to send an error message every time I try to install this plugin, is there a way to install manually?

**Comment by multicolour** [comment]
I'm also having the same issue.

**Comment by OGKevin** [comment]
hmm might be the new version, lemme try and reproduce. 

I test the code by installing manually 😓.
Guess is should make installing via obsidian also part of my test plan 🙈.

**Comment by OGKevin** [comment]
Im actually not sure, the install says 404 not found, meaning that Obsidian can't find an asset about this plugin, I'm not sure what it can't find. 

For manual install: https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/v1.5.1
You should be able to just download that zip and extract it in your plugin folder, that's basically what Obsidian does.

**Comment by OGKevin** [comment]
Lemme know if you still have issues. 
I just tested it and it seems to work for me 🤞🏾
