### ISSUE TITLE
Error during import of KoboReader.sqlite

### ISSUE THREAD

**Issue by choobacca-bacca** [OGKevin/obsidian-kobo-highlights-import#152]
`Error: bookmark seems to link to a non existing content: ops/xhtml/appendixb.html
    at HighlightService.eval (plugin:obsidian-kobo-highlights-importer-plugin:17348:17)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-kobo-highlights-importer-plugin:41:24)`

Upon selecting extract from the KoboReader.sqlite file, I receive this error. Unsure on how to proceed from here. Device details are as follows:
Kobo Libra 2
Software version: 4.37.21586 (42535ad976, 7/6/23)

First time downloading and trying to use the plugin from the community plugin store, and here is my settings. Thank you and appreciate any guidance.
![Image 16-7-23 at 6 07 PM](https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/78672342/304bead1-e094-4864-a962-92107025a5b5)

**Comment by OGKevin** [comment]
@choobacca-bacca are you comfortable executing queries on your sql database? 

It seems that the code has found a bookmark/highlight, but cannot find the corresponding content/book in the database.

Cloud be that the book as deleted but somehow the bookmarks where not cleaned up? 
Or it could be that this newer version of kobo is doing something funny, I personally haven't updated my kobo in ages tbh. 

But, nevertheless, if we can have a peak inside your DB to find out why there is a highlight with a potential broken reference t a book, would be a good start.

**Comment by choobacca-bacca** [comment]
Yup, I'm comfortable executing queries on my sql database. But maybe you're right on the book might not be in the database, as the book might have been returned (I borrow books sometimes from my library)

**Comment by choobacca-bacca** [comment]
omg didn't even realise my password was stored inside this database :(, but thank you so much!
