### ISSUE TITLE
Possible to have chapter?

### ISSUE THREAD

**Issue by ironhak** [OGKevin/obsidian-kobo-highlights-import#186]
hello, is it possibile to have also chapter? So a note would populate like: 

```
### Chapter 1
- Highlight
- Highlight

### Chapter 2
- Highlight
...
...
```
Thank's

**Comment by OGKevin** [comment]
I'm not sure I'm understanding you correctly. Isn't this already how this plugin works? 

It gathers all the highlights by chapter and groups them accordingly. 

It could be that the book you're using is not "properly" represented in the database.
