### ISSUE TITLE
Instructions on how to obtain the sqlite database used by the test suite?

### ISSUE THREAD

**Issue by niciliketo** [OGKevin/obsidian-kobo-highlights-import#216]
I am trying to run the test suite for this repo. 
I am using the command
```bash
npm run test
```
However, when I run the tests, I get the following 
```
Error: ENOENT: no such file or directory, open 'KoboReader.sqlite'
```

Is it possible to provide instructions on how to obtain the sqlite database used by the test suite?

**Comment by OGKevin** [comment]
The database used in the test suite is my private database.
In the CI I pull the database and run the tests.
As it's my private DB, cant really share it.

If a shared test DB is really needed, I would need to create a dummy one containing anon data.
