### ISSUE TITLE
Import all book content

### ISSUE THREAD

**Issue by danicotillas** [OGKevin/obsidian-kobo-highlights-import#305]
Thanks for the plugin! Just great.
I would like to know if there is any chance to import all the book content to the note as well.
It would be very useful to me if I could read from the note the context where I did the highlight or comment.

Thanks!

**Comment by OGKevin** [comment]
With all the book content, you mean literally export the whole book? 
The book's content is not stored in the database, but in an .epub file on the device.
I think this feature is out of scope for this plugin, and you're better of using an .epub to .md conversion tool like https://pandoc.org/

**Comment by danicotillas** [comment]
Thanks for the answer. Right after I wrote that I just thought about what you are saying. Also that there would be some sort of Copyright problem aside.
Thanks for creating the plugin! It's really helpful to me!
