### ISSUE TITLE
bookmark seems to link to a non existing content

### ISSUE THREAD

**Issue by abovetheborg** [OGKevin/obsidian-kobo-highlights-import#315]
I have this error when I run the plugin in Obsidian
```
Error: bookmark seems to link to a non existing content: OEBPS/xhtml/73_Chapter.xhtml
    at HighlightService.eval (plugin:obsidian-kobo…ter-plugin:17348:17)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-kobo…porter-plugin:41:24)
```
Obsidian: 1.5.8
Plugin: 1.5.4

I don't know how to properly debug this. I appreciate all the help that can be provided.

**Comment by OGKevin** [comment]
This basically means, that there seems to be a bookmark in your database that points to a book that the plugin cannot find in the database.

`content: OEBPS/xhtml/73_Chapter.xhtml` you can try to find this entry manually in your database and see if its indeed missing or not.

**Comment by abovetheborg** [comment]
The entry was missing. I managed to solve the problem by clearing all annotations.
