### ISSUE TITLE
not getting template details

### ISSUE THREAD

**Issue by sims0702** [OGKevin/obsidian-kobo-highlights-import#316]
Hey, why I am not getting the template details. They are stored on the kobo, like the descriptions etc. but nothing else.

![image](https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/73917633/8d25a4bf-f9df-4842-b75a-0ba4a72aa886)

Thanks in advance!

**Comment by OGKevin** [comment]
What version of the plugin are you using?

**Comment by simeon2002** [comment]
hey @OGKevin, the latest version that was downloaded from the community plugins. V1.5.4

**Comment by simeon2002** [comment]
to be more specific, this is what I get:
![image](https://github.com/OGKevin/obsidian-kobo-highlights-import/assets/61100437/02a11c54-dd5d-4cab-a587-c20795709a73)

**Comment by simeon2002** [comment]
And if I look in calibre, I can see that there is a description, isb number author plublisher etc. defined.

**Comment by OGKevin** [comment]
Aah that was introduced in https://github.com/OGKevin/obsidian-kobo-highlights-import/pull/291

This will be available once #255 is merged.
I’ll try to get that merged this week.
Feel free to re-open in case that still doesn’t solve your issue.

If you don’t want to wait, you can manually install https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/1.6.0-beta.2 and get it sooner.
