### ISSUE TITLE
Bookmark column returned unexpected null

### ISSUE THREAD

**Issue by Mr-Sawyer** [OGKevin/obsidian-kobo-highlights-import#33]
Hello,
while trying to import my huge database (2695 highlights) I encountered this error:

"Bookmark column returned unexpected null"

After some trial and error, I found that my database, for some reason, had some highlights rows with a blank "text" column (not NULL, blank), and the plugin throws an error thinking the column is NULL.

Deleting those rows fixed the issue.

I suggest changing the SQL WHERE clause in the getAllBookmark() function to check if  `Text is not null and Text <> '' ` to fix it

**Comment by OGKevin** [comment]
Ha, I thought this code will actually never get executed 😅.

Thanks for the report! I'll modify the code to not crash like that.
