### ISSUE TITLE
Error filtering by contentId yielded more then 1 result

### ISSUE THREAD

**Issue by jjanvier** [OGKevin/obsidian-kobo-highlights-import#42]
Hello there :)

I got the following error when trying your plugin. Is there anything I can do to fix this?

```
plugin:obsidian-kobo-highlights-importer-plugin:17595 Error: filtering by contentId yielded more then 1 result: /mnt/onboard/Martraire, Cyrille/Living Documentation - Cyrille Martraire.kepub.epub!OEBPS!chap17.xhtml#leanpub-auto-accuracy-mechanism
    at Repository.eval (plugin:obsidian-kobo-highlights-importer-plugin:17442:15)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-kobo-highlights-importer-plugin:50:61)
    at new Promise (<anonymous>)
    at __async (plugin:obsidian-kobo-highlights-importer-plugin:34:10)
    at Repository.getContentLikeContentId (plugin:obsidian-kobo-highlights-importer-plugin:17432:12)
    at HighlightService.eval (plugin:obsidian-kobo-highlights-importer-plugin:17311:35)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-kobo-highlights-importer-plugin:37:24)
```

**Comment by OGKevin** [comment]
Oh, no 😩 this error I added for sanity, thinking it would never actually trigger in real live 😂. And behold, it actually did. 

I'll do some research next week and let you know.

**Comment by jjanvier** [comment]
Super, thanks :+1: 

Don't hesitate to ask for help.

Here is what I got by requesting the SQLite database.

```
select Title, ContentID, ChapterIDBookmarked, BookTitle from content where ContentID like '%Martraire, Cyrille/Living Documentation - Cyrille Martraire.kepub.epub!OEBPS!chap17.xhtml#leanpub-auto-accuracy-mechanism%'

Accuracy Mechanism|/mnt/onboard/Martraire, Cyrille/Living Documentation - Cyrille Martraire.kepub.epub!OEBPS!chap17.xhtml#leanpub-auto-accuracy-mechanism-2|/mnt/onboard/Martraire, Cyrille/Living Documentation - Cyrille Martraire.kepub.epub!OEBPS!chap17.xhtml|Living Documentation
Accuracy Mechanism for a reliable documentation for fast-changing projects|/mnt/onboard/Martraire, Cyrille/Living Documentation - Cyrille Martraire.kepub.epub!OEBPS!chap17.xhtml#leanpub-auto-accuracy-mechanism-for-a-reliable-documentation-for-fast-changing-projects-3|/mnt/onboard/Martraire, Cyrille/Living Documentation - Cyrille Martraire.kepub.epub!OEBPS!chap17.xhtml|Living Documentation

```

**Comment by OGKevin** [comment]
Wait a min, does this book have 2 chapters that happen to start with `leanpub-auto-accuracy-mechanism`? 

`leanpub-auto-accuracy-mechanism` and `leanpub-auto-accuracy-mechanism-for-a-reliable-documentation-for-fast-changing-projects`

Or, is this same book imported twice? Like 2 versions of the same book? 

When I wrote the logic of finding the right entry in the `content` table that correlates with the right entry in `Bookmark`, I did not think about the scenario where one would have 2 versions of the same book, or similar Title, book title and chapter name 🤯

**Comment by OGKevin** [comment]
Based on your answer I know how to try and implement a fix. As I'm not sure if your DB is just dirty or if my assumption about never having a duplicate match is incorrect.

**Comment by jjanvier** [comment]
Hello @OGKevin ! Thanks for the reply. I double-checked the database, and it seems fine. I do NOT have two versions of the same book.

This book has indeed two chapters starting by "Accuracy mechanism".

![2022-10-28-215338_3840x1080_scrot](https://user-images.githubusercontent.com/3691804/198721520-17a37e4b-0b40-472e-a62f-6dd2a901fe11.png)

**Comment by jjanvier** [comment]
This is such unlikely to happen that I think it's safe to assume you could not raise this exception, and return the first content matching.

**Comment by OGKevin** [comment]
Ah I see 👍🏾. Yea returning the first result would be a good solution. And then a warning log in console in case user is wondering if there is a miss match 👌🏾.

Thanks for the info!
I'll get on it in this week.

**Comment by OGKevin** [comment]
@jjanvier Please give https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/1.3.1 a try and let me know if its all good 🙏🏾

**Comment by jjanvier** [comment]
It works perfectly :+1: 
Thank you very much Kevin :pray:
