### ISSUE TITLE
Add support for exporting notes

### ISSUE THREAD

**Issue by OGKevin** [OGKevin/obsidian-kobo-highlights-import#6]
Add the ability to include notes made in the export.

Relates to: https://github.com/bitwiseops/obsidian-kobo-highlights-import/issues/2

**Comment by MichaelLepori** [comment]
Nice! Thank you @OGKevin

**Comment by OGKevin** [comment]
@MichaelLepori Are you able to do a test again, before I merge the MR?

**Comment by OGKevin** [comment]
@MichaelLepori Cool, could you give https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/1.3.0-beta.0 a try please 🙏🏾

**Comment by MichaelLepori** [comment]
Hi OGKevin,
Oh Man....that's nice what you did!!
Hier the Result:



Why ist there a space more on the first line?
I tried Multiline on the Note of a Highlight:

2nd Question:
How does it work with the sorting?
The first example ist the last Highlight Note on the top.The second example ist the last Note at the end.
Have a nice weekend.
All the Best.

-- Michael Lepori
 

    Il venerdì 16 settembre 2022 20:52:31 CEST, Kevin Hellemun ***@***.***> ha scritto:  
 
 


@MichaelLepori Cool, could you give https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/1.3.0-beta.0 a try please 🙏🏾

**Comment by OGKevin** [comment]
@MichaelLepori I think you wanted to send an attachment? I think that is not possible via email. You must do that via GitHub directly.

The code that touches ordering has no changes in this release 🤔 
I don't see any order issues in my diff.
The way ordering is done is based on the chapter the note has been taken. 
If you have 2 highlights within the same chapter, then the ordering can be incorrect 🤔
Is this what you are experiencing?

**Comment by MichaelLepori** [comment]
Yes, I sent you these Pictures: 

Can you see those now?

Thank you.


Michael Lepori 

Von meinem iPhone gesendet

**Comment by OGKevin** [comment]
@MichaelLepori Nope

**Comment by MichaelLepori** [comment]
@OGKevin I write hier on GitHub:
Hier the Result:
![image](https://user-images.githubusercontent.com/39479918/190888136-39352019-e54b-4497-88fa-88a8850cd58d.png)

![image](https://user-images.githubusercontent.com/39479918/190888142-149623c5-3b88-4b1d-9db5-5718c5b0a5f4.png)


Why ist there a space more on the first line?
![image](https://user-images.githubusercontent.com/39479918/190888151-b1d9a67c-80ca-43e0-8750-1ab9e62c6891.png)

I tried Multiline on the Note of a Highlight.

2nd Question:
How does it work with the sorting?
The first example ist the last Highlight Note on the top.The second example ist the last Note at the end.

**Comment by OGKevin** [comment]
@MichaelLepori  The extra space should be fixed in https://github.com/OGKevin/obsidian-kobo-highlights-import/releases/tag/1.3.0-beta.1.

Regarding sorting, it sorts based on an internal ID that is stored in the database: https://github.com/OGKevin/obsidian-kobo-highlights-import/blob/025c83508560dcf84caf3e79a67d2559c73d5db1/src/database/Highlight.ts#L80-L81

For some reason, the ID of chapter27 is sorted above the ID of chapter1. The only way to find out why is to see what the values of the ContentID is.

If you would like, I can add debug logging in the next release that you can use to extract this information, and then we can figure out why the sorting is not working for this book.
