### ISSUE TITLE
typo in src/settings/Settings.ts

### ISSUE THREAD

**Issue by tjex** [OGKevin/obsidian-kobo-highlights-import#82]
I was looking through the code and found these two typos. 

```
src/settings/Settings.ts
38:        this.add_temaplte_path();
59:    add_temaplte_path(): void {
```

the function is both declared and called as a misspelling. So everything is working fine of course, however it could be a recipe for a bug down the track.

I have fixed it on a branch and can push if I get granted access :~)

**Comment by OGKevin** [comment]
Thx for the report.

You can always fork this project and open a MR that way 👍🏾.

If you haven't by the time I look into it, Ill fix it myself 👌🏾

**Comment by tjex** [comment]
ah yeah woops. blanked on that. will do 👍
